apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector: 
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-appd
spec:
  replicas: 5
  selector:
    #matchLabels:
    #  app: second-app
    #  tier: backend
    matchExpressions:
      - {key: app, operator: In, values: [second-app]}
  template:
    metadata: 
      labels:
        app: second-app
        tier: backend
    spec: 
      containers:
        - name: second-node
          image: itzminos/kube-first
        # - name: ...
        #   image: ...
 